### ISSUE TITLE
Cloud init ?

### ISSUE THREAD

**Issue by senare** [glesys/terraform-provider-glesys#105]
How would I go about using this with Glesys ?

https://registry.terraform.io/providers/hashicorp/cloudinit/latest/docs

Would i need to have 2 impl ?

**Comment by norrland** [comment]
You can find information on how to use cloudconfig/cloud-init here: https://registry.terraform.io/providers/glesys/glesys/latest/docs/resources/server

Also here: https://github.com/glesys/API/wiki/Using-cloud-config-to-configure-you-KVM-server

**Comment by norrland** [comment]
@senare does that work for you?
