### ISSUE TITLE
DNS records are reported as existing even if they are missing

### ISSUE THREAD

**Issue by senare** [glesys/terraform-provider-glesys#126]
If I add a DNS A record using terraform and then delete it from the console it wont restore the entry ... 

several similar hard to describe issues seams to be present ...  I am guessing that there is an issue with ID or something ? 

I would expect it to sync up ensure that the declared DNS entry exists ?

**Comment by norrland** [comment]
I'll check if this is solved with #120 already. Otherwise I'll work on a fix for it.
