### ISSUE TITLE
Add ability to manage email alias ?

### ISSUE THREAD

**Issue by senare** [glesys/terraform-provider-glesys#142]
I am looking into using email alias a bit more and would like to be able to manage them as code some how ... but when i look at the provider and doc it seams I can create email account but not set upp and manage alias ?

**Comment by brother** [comment]
Sounds reasonable. Let's make it happen!

**Comment by norrland** [comment]
@senare please try the suggested changes in #143 , see if the changes makes sense.

**Comment by senare** [comment]
Awsome ! 

Bit of poor timing on my part here, but I will give it a go as soon as I get a chance !
