### ISSUE TITLE
glesys_dnsdomain_record loses track of TTL if field is unset

### ISSUE THREAD

**Issue by tazjin** [glesys/terraform-provider-glesys#37]
If a `glesys_dnsdomain_record` is configured with a TTL, and the explicit TTL setting is later removed (e.g. in order to revert to the default value) the provider loses track of this and does not attempt to reconcile the TTL.

This can cause problems if somebody assumes that the setting has been reverted back to the 3600 second default.

**Comment by norrland** [comment]
Do you have any example of this?
As the TTL field is optional, removing this from the terraform configuration will not instruct the provider to set a default TTL.
Doing a `terraform refresh && terraform show` would still show the current TTL value for a record.

**Comment by norrland** [comment]
Please reopen if still relevant.
