### ISSUE TITLE
Latest TF version?

### ISSUE THREAD

**Issue by jede** [glesys/terraform-provider-glesys#40]
Right now this only works in terraform 0.12, and the latest is 1.1.6. Are there any reason it cannot be upgraded? I would like to help out, just want to know if there is anything I'm missing before I start.

**Comment by norrland** [comment]
Hi, haven't been around to look at it unfortunately.
Nothing is blocking the upgrade except that someone has to do it. I'm unavailable until late this year. Feel free to send a PR if you do get it up and running with Terraform 1.x.

**Comment by norrland** [comment]
Can you give it a try again with Terraform 1.x? I've updated the docs in #49 for local dev.
